In [1]:
import itertools

In [4]:
f=open('./cars_2014.csv','r')
for i in range(20) :
    print(f.readline(),end="")

make,model
ACURA,ILX
ACURA,MDX
ACURA,RDX
ACURA,RLX
ACURA,TL
ACURA,TSX
ALFA ROMEO,4C
ALFA ROMEO,GIULIETTA
APRILIA,CAPONORD 1200
APRILIA,RSV4 FACTORY APRC ABS
APRILIA,RSV4 R APRC ABS
APRILIA,SHIVER 750
ARCTIC CAT,1000 XT
ARCTIC CAT,500 XT
ARCTIC CAT,550 XT
ARCTIC CAT,700 LTD
ARCTIC CAT,700 SUPER DUTY DIESEL
ARCTIC CAT,700 XT
ARCTIC CAT,90 2X4 4-STROKE

In [6]:
from collections import defaultdict
makes=defaultdict(int)

f=open('./cars_2014.csv','r')
for i in f :
    l,_=i.strip('\n').split(',')
    makes[l]+=1
for key,values in makes.items() :

    print(f'{key}={values}')

make=1
ACURA=6
ALFA ROMEO=2
APRILIA=4
ARCTIC CAT=96
ARGO=4
ASTON MARTIN=5
AUDI=27
BENTLEY=2
BLUE BIRD=1
BMW=86
BUGATTI=1
BUICK=5
CADILLAC=7
CAN-AM=61
CHEVROLET=33
CHRYSLER=2
DODGE=7
DUCATI=4
FERRARI=6
FIAT=2
FORD=34
FREIGHTLINER=7
GMC=12
HARLEY DAVIDSON=29
HINO=7
HONDA=91
HUSABERG=4
HUSQVARNA=9
HYUNDAI=13
INDIAN=3
INFINITI=8
JAGUAR=9
JEEP=5
JOHN DEERE=19
KAWASAKI=59
KENWORTH=11
KIA=10
KTM=13
KUBOTA=4
KYMCO=28
LAMBORGHINI=2
LAND ROVER=6
LEXUS=14
LINCOLN=6
LOTUS=1
MACK=9
MASERATI=3
MAZDA=5
MCLAREN=2
MERCEDES-BENZ=60
MINI=3
MITSUBISHI=8
NISSAN=24
PEUGEOT=3
POLARIS=101
PORSCHE=4
RAM=6
RENAULT=4
ROLLS ROYCE=3
SCION=5
SEAT=3
SKI-DOO=67
SMART=1
SRT=1
SUBARU=10
SUZUKI=48
TESLA=2
TOYOTA=19
TRIUMPH=10
VESPA=4
VICTORY=14
VOLKSWAGEN=16
VOLVO=8
YAMAHA=110

In [21]:
from itertools import *

f=open('./cars_2014.csv','r')
next(f)
l=groupby(f,key= lambda x : (x.strip('\n').split(','))[0])
for i in l :
    print(i[0],len(list(i[1])))

ACURA 6
ALFA ROMEO 2
APRILIA 4
ARCTIC CAT 96
ARGO 4
ASTON MARTIN 5
AUDI 27
BENTLEY 2
BLUE BIRD 1
BMW 86
BUGATTI 1
BUICK 5
CADILLAC 7
CAN-AM 61
CHEVROLET 33
CHRYSLER 2
DODGE 7
DUCATI 4
FERRARI 6
FIAT 2
FORD 34
FREIGHTLINER 7
GMC 12
HARLEY DAVIDSON 29
HINO 7
HONDA 91
HUSABERG 4
HUSQVARNA 9
HYUNDAI 13
INDIAN 3
INFINITI 8
JAGUAR 9
JEEP 5
JOHN DEERE 19
KAWASAKI 59
KENWORTH 11
KIA 10
KTM 13
KUBOTA 4
KYMCO 28
LAMBORGHINI 2
LAND ROVER 6
LEXUS 14
LINCOLN 6
LOTUS 1
MACK 9
MASERATI 3
MAZDA 5
MCLAREN 2
MERCEDES-BENZ 60
MINI 3
MITSUBISHI 8
NISSAN 24
PEUGEOT 3
POLARIS 101
PORSCHE 4
RAM 6
RENAULT 4
ROLLS ROYCE 3
SCION 5
SEAT 3
SKI-DOO 67
SMART 1
SRT 1
SUBARU 10
SUZUKI 48
TESLA 2
TOYOTA 19
TRIUMPH 10
VESPA 4
VICTORY 14
VOLKSWAGEN 16
VOLVO 8
YAMAHA 110

In [52]:
l=[1,2,2,3,4,5,3,2,2]
g=groupby(l)
for i in g :
    print(i[0],list(i[1]))

1 [1]
2 [2, 2]
3 [3]
4 [4]
5 [5]
3 [3]
2 [2, 2]

In [65]:
from itertools import *
from operator import *
class fun :
    # for i in range(n):
    #     yield i**2 , i**3
    def __init__(self,n):
        self.n=n
       
    def __iter__(self):
        return self.funiter(self.n) 
    
    class funiter :
      def __init__(self,n) -> None:
         self.n=n
         self.i=0

      def __iter__(self) :
         return self 

      def __next__(self): 
        if self.i >= self.n  :
           raise StopIteration
        else :
            r=self.i**2
            m=self.i**3
            self.i+=1
            return r,m


o1=fun(7)
k=iter(o1)
print(next(k))
print(next(k))
for i in o1:
    print(i)
# print(max(o1))  
# o1=fun(7)
# print(list(islice(o1,0,5)))
# o1=fun(7)
# print(list(starmap(mul ,o1)))
# o1=fun(7)
# print(len(o1))

call
l
(0, 0)
l
(1, 1)
call
l
(0, 0)
l
(1, 1)
l
(4, 8)
l
(9, 27)
l
(16, 64)
l
(25, 125)
l
(36, 216)
l